version: '3.7'

services:
   backend-server:
    build: . # Pass the context to build, usually it's the current context.
    image:  ghcr.io/nathansegers/advfs/demo:v1.2.3
    entrypoint: ['node', 'server.js'] # The actual entrypoint of the container to run the server file
    # entrypoint: ['tail', '-f', '/dev/null'] # Uncomment to keep alive and able to debug
    environment:
      PORT: 3000
      NODE_ENV: 'development'
    ports:
      - 3000:3000
    volumes:
      - ./src/config/service-account.json:/code/dist/config/service-account.json